### ISSUE TITLE
Develop a mask processor

### ISSUE THREAD

**Issue by iagora** [iagora/fiddle#1]
Develop a mask processor companion app to fiddle. Similar to hashcat's.
So I can specify CPFs, like:

- `?d?d?d.?d?d?d.?d?d?d-?d?d` (has `.` and already has digits, just verify print to `stderr` if error and move on);
- `?d?d?d.?d?d?d.?d?d?d-` (has `.`, doesn't have digits but has the hyphen, have to generate the digits and put it after hyphen);
- `?d?d?d?d?d?d?d?d?d-?d?d` (doesn´t have `.`, has digits after hyphen, just verify and print to `stderr` if error and move on);
- And so on.

**Comment by roycewilliams** [comment]
Just curious ... are there features you're looking for that `maskprocessor` doesn't already have? Or are you just looking to create your own standalone utility?

**Comment by iagora** [comment]
It absolutely already has. And even when I'm done, `maskprocessor` will still be more powerful, since I want just a subsection of its features. The whole purpose of the project is spending some time with OCaml.

Even `fiddle` itself is a non-GPU powered `hashcat` that deals just specifically with CPFs.

**Comment by iagora** [comment]
Dang it, I closed it by mistake.
